version: "3.7"
services: 
  backend_pos:
    image: "aldifarzum/dockerpos-backend:v1.0.0.2"    
    volumes:
      - ./backend/logfile:/backend/logfile
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 50M
    networks:
      - netnetwork 
    environment:
        PGUSER: admin
        PGHOST: 54.237.63.193
        PGDATABASE: postgres
        PASSWORD: secret
        PGPORT: 5432
        SERVICEPORT: 4500
        REDIS_PORT: 6379
        REDIS_PASSWORD: aldi1234
        REDIS_HOST: 54.237.63.193
  frontend_pos:    
    image: "aldifarzum/dockerpos-frontend:v1.0.0.1"
    ports:
      - 9191:80
    networks:
      - netnetwork
    depends_on:
      - backend_pos
    environment:
     -  VUE_APP_URL=http://54.237.27.238:9191/backend/
     -  VUE_APP_STATIC_URL=http://54.237.27.238:9191/backend/
    volumes: 
      - ./frontend:/dist/public
networks:
  netnetwork:
      
volumes:
  pgdata:
  pgadmin-data:
